require("__aoe__/prototypes/recipes/age0-recipes")
require("__aoe__/prototypes/recipes/age1-recipes")
require("__aoe__/prototypes/recipes/age2-recipes")
require("__aoe__/prototypes/recipes/age3-recipes")
require("__aoe__/prototypes/recipes/age4-recipes")
require("__aoe__/prototypes/recipes/vacuum-recipes")