require("__aoe__/prototypes/items/age0-items")
require("__aoe__/prototypes/items/age1-items")
require("__aoe__/prototypes/items/age2-items")
require("__aoe__/prototypes/items/age3-items")
require("__aoe__/prototypes/items/age4-items")
require("__aoe__/prototypes/items/age5-items")