function ms_data()
    return {
        ["Age of Creation"] = {
            required_mods = {"ageofcreation", "space-age"},
            milestones = {
                {type="group", name="Science"},
                {type="item", name="aoc-science-01", quantity=1},
                {type="item", name="aoc-science-01", quantity=1000, next="x10"},
                {type="item", name="aoc-science-02", quantity=1},
                {type="item", name="aoc-science-02", quantity=1000, next="x10"},
                {type="item", name="aoc-science-03", quantity=1},
                {type="item", name="aoc-science-03", quantity=1000, next="x10"},
                {type="item", name="aoc-science-04", quantity=1},
                {type="item", name="aoc-science-04", quantity=1000, next="x10"},
                {type="item", name="aoc-science-05", quantity=1},
                {type="item", name="aoc-science-05", quantity=1000, next="x10"},
                {type="item", name="aoc-science-06", quantity=1},
                {type="item", name="aoc-science-06", quantity=1000, next="x10"},
                {type="item", name="aoc-science-07", quantity=1},
                {type="item", name="aoc-science-07", quantity=1000, next="x10"},
                {type="item", name="aoc-science-08", quantity=1},
                {type="item", name="aoc-science-08", quantity=1000, next="x10"},

                {type="group", name="Farming Age (Age 1)"},
                {type="item", name="iron-plate", quantity=1},
                {type="item", name="aoc-glass", quantity=1},
                {type="item", name="aoc-log", quantity=1},
                {type="item", name="aoc-kelp", quantity=1},
                {type="item", name="aoc-tea-leaves", quantity=1},
                {type="item", name="aoc-coffee-plant", quantity=1},
                {type="item", name="aoc-latex-rubber", quantity=1},
                {type="item", name="transport-belt", quantity=1},
                {type="item", name="transport-belt",  quantity=1000, next="x10"},
                {type="item", name="aoc-flax", quantity=1},
                {type="item", name="copper-plate", quantity=1},

                {type="group", name="Electric Age (Age 2)"},
                {type="item", name="steel-plate", quantity=1},
                {type="item", name="electronic-circuit", quantity=1},
                {type="item", name="electronic-circuit", quantity=1000, next="x10"},
                {type="item", name="aoc-steel-machine-hull", quantity=1},
                {type="item", name="inserter", quantity=1},
                {type="item", name="assembling-machine-2", quantity=1},
                {type="item", name="steel-furnace", quantity=1},
                {type="item", name="coal", quantity=1},
                {type="item", name="aoc-aluminium-plate", quantity=1},
                {type="item", name="aoc-quartz-dust", quantity=1},
                {type="item", name="aoc-tin-plate", quantity=1},
                {type="item", name="concrete", quantity=1},
                {type="item", name="raw-fish", quantity=1},

                {type="group", name="Agriculture Age (Age 3)"},
                {type="item", name="aoc-spruce-tree", quantity=1},
                {type="item", name="aoc-rubber-tree", quantity=1},
                {type="item", name="aoc-apple-tree", quantity=1},
                {type="item", name="aoc-olive-tree", quantity=1},
                {type="item", name="aoc-grass", quantity=1},
                {type="item", name="aoc-maize", quantity=1},
                {type="item", name="aoc-soybeans", quantity=1},
                {type="item", name="aoc-chicken", quantity=1},
                {type="item", name="aoc-fertilizer", quantity=1},
                {type="item", name="aoc-sheep", quantity=1},
                {type="item", name="aoc-cow", quantity=1},
                {type="item", name="aoc-ox", quantity=1},
                {type="item", name="aoc-bronze-plate", quantity=1},

                {type="group", name="Metallurgy Age (Age 4)"},
                {type="item", name="rail", quantity=1},
                {type="item", name="rail", quantity=1000, next="x10"},
                {type="item", name="aoc-nickel-plate", quantity=1},
                {type="item", name="aoc-zinc-plate", quantity=1},
                {type="item", name="aoc-lead-plate", quantity=1},
                {type="item", name="aoc-silver-plate", quantity=1},
                {type="item", name="aoc-chromium-plate", quantity=1},
                {type="item", name="aoc-gold-plate", quantity=1},
                {type="item", name="tungsten-plate", quantity=1},
                {type="item", name="aoc-diamond", quantity=1},
                {type="item", name="aoc-solder", quantity=1},
                {type="item", name="aoc-electrum", quantity=1},
                {type="item", name="aoc-brass", quantity=1},
                {type="item", name="aoc-aluminium-bronze", quantity=1},
                {type="item", name="aoc-silicon", quantity=1},
                {type="item", name="aoc-stainless-steel", quantity=1},
                {type="item", name="aoc-animal-food", quantity=1},
                {type="item", name="fast-inserter", quantity=1},
                {type="item", name="assembling-machine-3", quantity=1},
                {type="item", name="advanced-circuit", quantity=1},
                {type="item", name="advanced-circuit", quantity=1000, next="x10"},
                {type="item", name="electric-furnace", quantity=1},
                {type="item", name="plastic-bar", quantity=1},

                {type="group", name= "Petrochem Age (Age 5)"},
                {type="item", name="light-armor", quantity=1},
                {type="fluid", name="crude-oil", quantity=1},
                {type="item", name="aoc-rubber", quantity=1},
                {type="fluid", name="aoc-drilling-fluid", quantity=1},
                {type="item", name="aoc-fertilizer-2", quantity=1},
                {type="item", name="bulk-inserter", quantity=1},
                {type="item", name="fast-transport-belt", quantity=1},
                {type="item", name="fast-transport-belt", quantity=1000, next="x10"},
                {type="item", name="electric-engine-unit", quantity=1},
                {type="item", name="aoc-laser",  quantity=1},
                {type="item", name="aoc-queen-aoc-honey", quantity=1},
                {type="item", name="aoc-queen-aoc-royal-jelly", quantity=1},
                {type="item", name="bee-construction",  quantity=1},
                {type="item", name="bee-logistic",  quantity=1},
                {type="item", name="aoc-epoxy-resin-solid",  quantity=1},
                {type="item", name="processing-unit", quantity=1},
                {type="item", name="processing-unit", quantity=1000, next="x10"},
                {type="item", name="aoc-nauvium-plate", quantity=1},

                {type="group", name= "Magic Age (Age 6)"},
                {type="fluid", name="aoc-drilling-fluid-magical", quantity=1},
                {type="fluid", name="aoc-starlight", quantity=1},
                {type="item", name="ice", quantity=1},
                {type="item", name="aoc-lotus-flower", quantity=1},
                {type="fluid", name="aoc-mana", quantity=1},
                {type="item", name="aoc-platinum-plate", quantity=1},
                {type="item", name="aoc-enderium-plate", quantity=1},
                {type="item", name="aoc-teleportation-core", quantity=1},
                {type="item", name="aoc-planet-space", quantity=1},

                {type="group", name= "Space Age (Age 7)"},
                {type="item", name="aoc-titanium-plate", quantity=1},
                {type="item", name="productivity-module", quantity=1},
                {type="item", name="aoc-nuclear-reactor", quantity=1},
                {type="item", name="uranium-238", quantity=1},
                {type="item_consumption", name="space-platform-starter-pack", quantity=1},
                {type="item", name="construction-robot", quantity=1},
                {type="item", name="logistic-robot", quantity=1},
                {type="fluid", name="thruster-fuel", quantity=1},
                {type="item", name="aoc-life-catalyst", quantity=1},
                {type="item", name="aoc-vulcanus-chest", quantity=1}
            }
        }
    }
end