require("__aoe__/prototypes/techs/age1-techs")
require("__aoe__/prototypes/techs/age2-techs")
require("__aoe__/prototypes/techs/age3-techs")
require("__aoe__/prototypes/techs/age4-techs")
require("__aoe__/prototypes/techs/qol-techs")