require("__ageofcreation__/prototypes/techs/age1-techs")
require("__ageofcreation__/prototypes/techs/age2-techs")
require("__ageofcreation__/prototypes/techs/age3-techs")
require("__ageofcreation__/prototypes/techs/age4-techs")
require("__ageofcreation__/prototypes/techs/age5-techs")
require("__ageofcreation__/prototypes/techs/age6-techs")
require("__ageofcreation__/prototypes/techs/age7-techs")
require("__ageofcreation__/prototypes/techs/qol-techs")